=== gPinato/ApertureProject/SWE/Solo per Maso/Tecweb2.0/roba veronica/retecweb (1)/appuntamenti.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
    xmlns="http://tecnologie-web.studenti.math.unipd.it/tecweb/~gpinato"
    targetNamespace="http://tecnologie-web.studenti.math.unipd.it/tecweb/~gpinato"
    elementFormDefault="qualified">

<xs:element name="lista">
	<xs:complexType>
		<xs:sequence>
			<xs:element name="appuntamento" minOccurs="0" maxOccurs="unbounded">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="numero">
							<xs:simpleType>
								<xs:restriction base="xs:integer">
									<xs:maxExclusive value="32"/>
								</xs:restriction>
							</xs:simpleType>
						</xs:element>
						<xs:element name="nmese">
							<xs:simpleType>
								<xs:restriction base="xs:integer">
									<xs:maxExclusive value="13"/>
								</xs:restriction>
							</xs:simpleType>
						</xs:element>
						<xs:element name="giorno">
							<xs:simpleType>
								<xs:restriction base="xs:string">
									<xs:enumeration value="Monday"/>
									<xs:enumeration value="Tuesday"/>
									<xs:enumeration value="Wednesday"/>
									<xs:enumeration value="Thursday"/>
									<xs:enumeration value="Friday"/>
									<xs:enumeration value="Saturday"/>
									<xs:enumeration value="Sunday"/>
								</xs:restriction>
							</xs:simpleType>
						</xs:element>
						<xs:element name="mese">
							<xs:simpleType>
								<xs:restriction base="xs:string">
									<xs:enumeration value="January"/>
									<xs:enumeration value="February"/>
									<xs:enumeration value="March"/>
									<xs:enumeration value="April"/>
									<xs:enumeration value="May"/>
									<xs:enumeration value="June"/>
									<xs:enumeration value="July"/>
									<xs:enumeration value="August"/>
									<xs:enumeration value="September"/>
									<xs:enumeration value="October"/>
									<xs:enumeration value="November"/>
									<xs:enumeration value="December"/>
								</xs:restriction>
							</xs:simpleType>
						</xs:element>
						<xs:element name="anno" type="xs:integer" />
						<xs:element name="utente" type="xs:string" />
						<xs:element name="nota" type="xs:string" />
					</xs:sequence>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
</xs:element>

</xs:schema>

=== gPinato/ApertureProject/SWE/Solo per Maso/Tecweb2.0/roba veronica/retecweb (1)/appuntamenti.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="appuntamenti.xsl"?>
<lista xmlns="http://tecnologie-web.studenti.math.unipd.it/tecweb/~gpinato" 
	xmlns:xs="http://www.w3.org/2001/XMLSchema-instance" 
	xs:schemaLocation="http://tecnologie-web.studenti.math.unipd.it/tecweb/~gpinato appuntamenti.xsd">

	<appuntamento>
		<numero>10</numero>
		<nmese>11</nmese>
		<giorno>Sunday</giorno>
		<mese>November</mese>
		<anno>2013</anno>
		<utente>Ciop</utente>
		<nota>ojhggft</nota>
	</appuntamento>

	<appuntamento>
		<numero>4</numero>
		<nmese>11</nmese>
		<giorno>Monday</giorno>
		<mese>November</mese>
		<anno>2013</anno>
		<utente>Pippo</utente>
		<nota>ojhggft</nota>
	</appuntamento>

	<appuntamento>
		<numero>6</numero>
		<nmese>11</nmese>
		<giorno>Wednesday</giorno>
		<mese>November</mese>
		<anno>2013</anno>
		<utente>Paperino</utente>
		<nota>iyugu oiu</nota>
	</appuntamento>


	<appuntamento>
		<numero>12</numero>
		<nmese>11</nmese>
		<giorno>Tuesday</giorno>
		<mese>November</mese>
		<anno>2013</anno>
		<utente>Willy</utente>
		<nota>yuu yui</nota>
	</appuntamento>


	<appuntamento>
		<numero>13</numero>
		<nmese>11</nmese>
		<giorno>Wednesday</giorno>
		<mese>November</mese>
		<anno>2013</anno>
		<utente>Silvestro</utente>
		<nota>ojhggft</nota>
	</appuntamento>

	<appuntamento>
		<numero>21</numero>
		<nmese>11</nmese>
		<giorno>Thursday</giorno>
		<mese>November</mese>
		<anno>2013</anno>
		<utente>Minnie</utente>
		<nota>ah ah ah</nota>
	</appuntamento>

	<appuntamento>
		<numero>2</numero>
		<nmese>12</nmese>
		<giorno>Monday</giorno>
		<mese>December</mese>
		<anno>2013</anno>
		<utente>Pippo</utente>
		<nota>ah ah ah</nota>
	</appuntamento>

</lista>
