=== gPinato/ApertureProject/SWE/Solo per Maso/Tecweb2.0/cgi-bin/appuntamenti.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
    xmlns="http://tecnologie-web.studenti.math.unipd.it/tecweb/~gpinato"
    targetNamespace="http://tecnologie-web.studenti.math.unipd.it/tecweb/~gpinato"
    elementFormDefault="qualified">

<xs:element name="lista">
	<xs:complexType>
		<xs:sequence>
			<xs:element name="appuntamento" minOccurs="0" maxOccurs="unbounded">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="numero">
							<xs:simpleType>
								<xs:restriction base="xs:integer">
									<xs:maxExclusive value="32"/>
								</xs:restriction>
							</xs:simpleType>
						</xs:element>
						<xs:element name="nmese">
							<xs:simpleType>
								<xs:restriction base="xs:integer">
									<xs:maxExclusive value="13"/>
								</xs:restriction>
							</xs:simpleType>
						</xs:element>
						<xs:element name="anno" type="xs:integer" />
						<xs:element name="utente" type="xs:string" />
						<xs:element name="nota" minOccurs="0" type="xs:string" />
					</xs:sequence>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
</xs:element>

</xs:schema>

=== gPinato/ApertureProject/SWE/Solo per Maso/Tecweb2.0/cgi-bin/appuntamenti.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="appuntamenti.xsl"?>
<lista xmlns="http://tecnologie-web.studenti.math.unipd.it/tecweb/~gpinato" xmlns:xs="http://www.w3.org/2001/XMLSchema-instance" schemaLocation="http://tecnologie-web.studenti.math.unipd.it/tecweb/~gpinato appuntamenti.xsd">

	<appuntamento>
		<numero>24</numero>
		<nmese>1</nmese>
		<anno>2014</anno>
		<utente>Ciop</utente>
		<nota>ojhggft</nota>
	</appuntamento>
	
	<appuntamento>
		<numero>30</numero>
		<nmese>1</nmese>
		<anno>2014</anno>
		<utente>Ciop</utente>
		<nota>ojhggft</nota>
	</appuntamento>
	
	<appuntamento>
		<numero>10</numero>
		<nmese>2</nmese>
		<anno>2014</anno>
		<utente>Ciop</utente>
		<nota>ojhggft</nota>
	</appuntamento>
	



<appuntamento>
               <numero>2</numero>
               <nmese>2</nmese>
               <anno>2014</anno>
               <utente>maso</utente>
               <nota>ojhggft</nota>
               </appuntamento><appuntamento>
               <numero>20</numero>
               <nmese>2</nmese>
               
               <anno>2014</anno>
               <utente>jack</utente>
               
               </appuntamento><appuntamento>
               <numero>21</numero>
               <nmese>2</nmese>
               
               <anno>2014</anno>
               <utente>jack</utente>
               
               </appuntamento></lista>
