=== gPinato/ApertureProject/SWE/Solo per Maso/Tecweb2.0/cgi-bin/user.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
    xmlns="http://tecnologie-web.studenti.math.unipd.it/tecweb/~gpinato"
    targetNamespace="http://tecnologie-web.studenti.math.unipd.it/tecweb/~gpinato"
    elementFormDefault="qualified">

<xs:element name="userlist">
	<xs:complexType>
		<xs:sequence>
			<xs:element name="user" minOccurs="0" maxOccurs="unbounded">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="username" type="xs:string" />
						<xs:element name="password" type="xs:string" />
						<xs:element name="email" type="xs:string" />
					</xs:sequence>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
</xs:element>

</xs:schema>

=== gPinato/ApertureProject/SWE/Solo per Maso/Tecweb2.0/cgi-bin/user.xml
<?xml version="1.0" encoding="UTF-8"?>
<userlist xmlns="http://tecnologie-web.studenti.math.unipd.it/tecweb/~gpinato" xmlns:xs="http://www.w3.org/2001/XMLSchema-instance" xs:schemaLocation="http://tecnologie-web.studenti.math.unipd.it/tecweb/~gpinato user.xsd">
<user>
              <username>b3daa77b4c04a9551b8781d03191fe098f325e67</username>
               <password>b3daa77b4c04a9551b8781d03191fe098f325e67</password>
			   <email>da39a3ee5e6b4b0d3255bfef95601890afd80709</email>
				</user><user>
               <username>a1881c06eec96db9901c7bbfe41c42a3f08e9cb4</username>
               <password>a1881c06eec96db9901c7bbfe41c42a3f08e9cb4</password>
			   <email>da39a3ee5e6b4b0d3255bfef95601890afd80709</email>
				</user><user>
               <username>d033e22ae348aeb5660fc2140aec35850c4da997</username>
               <password>d033e22ae348aeb5660fc2140aec35850c4da997</password>
			   <email>da39a3ee5e6b4b0d3255bfef95601890afd80709</email>
				</user><user>
               <username>a5f90ce2374a35764a9e8361b67e03c84374879c</username>
               <password>e057d4ea363fbab414a874371da253dba3d713bc</password>
			   <email>a88b7dcd1a9e3e17770bbaa6d7515b31a2d7e85d</email>
				</user><user>
<username>f10e2821bbbea527ea02200352313bc059445190</username>
<password>2cdd4c1add11499bbdf36fded91e677d8caf516a</password>
<email>a88b7dcd1a9e3e17770bbaa6d7515b31a2d7e85d</email>
</user></userlist>
